version: '3.8'
services:
  react-app:
    build:
      context: frontend
    ports:
      - 80:3000
    expose:
      - 3000
    depends_on:
      - rest-service

  rest-service:
    build:
      context: rest-service
      target: development
    ports:
      - '8000:8000'
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/scrimify
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=20030504Sta
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=scrimify
      - MYSQL_PASSWORD=20030504Sta
      - MYSQL_DATABASE=scrimify
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config:
